 baseURL = "/"
languageCode = "en-us"
title = "APA DAnalysis"
theme = "hugo-hero-theme"
logo= "apa logo.svg"

[module.hugoVersion]
extended = "yes"
min = "0.92.0"

[params]
google_analytics_id = "/"

  [params.homepage_meta_tags]
  meta_description = "APA DAnalysis is a website which shows Differential analysis results of two R packages and comparison of these packages"
  meta_og_description = "APA DAnalysis is a website which shows Differential analysis results of two R packages and comparison of these packages"
  meta_og_image = "https://images.unsplash.com/photo-1551288049-bebda4e38f71?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80"
  meta_og_title = "Alternative polyadenylation differential analysis"
  meta_og_type = "website"
  meta_og_url = "https://mywebsite.app"
  meta_twitter_card = "summary"
  meta_twitter_creator = "@noor070"
  meta_twitter_site = "@noor070"

  [params.logo]
  alt = "APA analysis"
  desktop = "images/logo.svg"
  desktop_height = "29px"
  desktop_width = "217px"
  mobile = "images/logo-mobile.svg"
  mobile_height = "36px"
  mobile_width = "36px"

[[menu.main]]
name = "Services"
url = "/services/"
weight = 1

[[menu.main]]
name = "Work"
url = "/work/"
weight = 2

[[menu.main]]
name = "About"
url = "/about/"
weight = 3

[[menu.main]]
name = "History"
url = "/history/"
weight = 3

[[menu.main]]
name = "Contact"
url = "/contact/"
weight = 4

[permalinks]
pages = "/:filename/"
post = "/:year/:month/:day/:slug/"
